In [1]:
import pandas as pd
import pickle

In [3]:
dataset = pd.read_csv("../50_Startups.csv")
dataset = pd.get_dummies(dataset, drop_first=True)
dataset = dataset.astype(int)
dataset

R&D Spend  Administration  Marketing Spend  Profit  State_Florida  \
0      165349          136897           471784  192261              0   
1      162597          151377           443898  191792              0   
2      153441          101145           407934  191050              1   
3      144372          118671           383199  182901              0   
4      142107           91391           366168  166187              1   
5      131876           99814           362861  156991              0   
6      134615          147198           127716  156122              0   
7      130298          145530           323876  155752              1   
8      120542          148718           311613  152211              0   
9      123334          108679           304981  149759              0   
10     101913          110594           229160  146121              1   
11     100671           91790           249744  144259              0   
12      93863          127320           249839  141585              1   
13      91992          135495           252664  134307              0   
14     119943          156547           256512  132602              1   
15     114523          122616           261776  129917              0   
16      78013          121597           264346  126992              0   
17      94657          145077           282574  125370              0   
18      91749          114175           294919  124266              1   
19      86419          153514                0  122776              0   
20      76253          113867           298664  118474              0   
21      78389          153773           299737  111313              0   
22      73994          122782           303319  110352              1   
23      67532          105751           304768  108733              1   
24      77044           99281           140574  108552              0   
25      64664          139553           137962  107404              0   
26      75328          144135           134050  105733              1   
27      72107          127864           353183  105008              0   
28      66051          182645           118148  103282              1   
29      65605          153032           107138  101004              0   
30      61994          115641            91131   99937              1   
31      61136          152701            88218   97483              0   
32      63408          129219            46085   97427              0   
33      55493          103057           214634   96778              1   
34      46426          157693           210797   96712              0   
35      46014           85047           205517   96479              0   
36      28663          127056           201126   90708              1   
37      44069           51283           197029   89949              0   
38      20229           65947           185265   81229              0   
39      38558           82982           174999   81005              0   
40      28754          118546           172795   78239              0   
41      27892           84710           164470   77798              1   
42      23640           96189           148001   71498              0   
43      15505          127382            35534   69758              0   
44      22177          154806            28334   65200              0   
45       1000          124153             1903   64926              0   
46       1315          115816           297114   49490              1   
47          0          135426                0   42559              0   
48        542           51743                0   35673              0   
49          0          116983            45173   14681              0   

    State_New York  
0                1  
1                0  
2                0  
3                1  
4                0  
5                1  
6                0  
7                0  
8                1  
9                0  
10               0  
11               0  
12     

In [5]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [7]:
independent = dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]
dependent = dataset['Profit']

In [9]:
#split Training and Test datasets
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(independent, dependent, test_size=0.30, random_state = 0)

In [11]:
#Standardisation (Defined range of datasets) the Train and Test data
from sklearn.preprocessing import StandardScaler
scX = StandardScaler()
xTrain = scX.fit_transform(xTrain)
xTest = scX.transform(xTest)

# Save the fitted scaler
with open('scalerX.pkl', 'wb') as f:
    pickle.dump(scX, f)

In [13]:
import numpy as np
scY = StandardScaler()
# Convert Series to NumPy array, then reshape
yTrain_np = yTrain.values.reshape(-1, 1)
yTest_np = yTest.values.reshape(-1, 1)

# Fit and transform
yTrain_scaled = scY.fit_transform(yTrain_np)
yTest_scaled = scY.transform(yTest_np)
# Save the fitted scaler
with open('scalerY.pkl', 'wb') as f:
    pickle.dump(scY, f)

In [15]:
#model creation
from sklearn.svm import SVR
regressor = SVR(kernel="linear")

regressor.fit(xTrain, yTrain)

SVR(kernel='linear')

In [17]:
regressor.n_support_

array([34], dtype=int32)

In [19]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34],
      dtype=int32)

In [21]:
yPred = regressor.predict(xTest)

In [23]:
#Metrics validation using r2 score function
from sklearn.metrics import r2_score
rScore = r2_score(yTest, yPred)
rScore

-0.055698007950230055

In [25]:
fileName = "Final_SVMR_PreBoth_Model.sav"
pickle.dump(regressor, open(fileName, 'wb'))

In [27]:
preInput = scX.transform([[1300,12000,4000,0,1]])
preInput

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.46754484, -4.33834816, -1.50743981, -0.5       ,  1.30088727]])

In [29]:
loaded_model=pickle.load(open("Final_SVMR_PreBoth_Model.sav", 'rb'))
result=loaded_model.predict(preInput)
result

array([108603.27619641])

In [ ]:
preOutput = scY.inverse_transform(result.reshape(-1, 1))
preOutput